# Generated by Django 4.2.9 on 2024-01-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=120)),
                ('aadhar', models.IntegerField()),
                ('station', models.CharField(max_length=120)),
                ('complain', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
