# Generated by Django 4.2.9 on 2024-01-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_rename_complain_complaint_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (-1, 'Declined')], default=0),
        ),
    ]
